services:
  rijan_wa:
    image: teguh02/rijan_wa:latest
    container_name: rijan_wa
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - rijan_wa_data:/app/data
      - rijan_wa_sessions:/app/sessions
      - rijan_wa_logs:/app/logs

volumes:
  rijan_wa_data:
  rijan_wa_sessions:
  rijan_wa_logs:
